name: dinosar
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12
  - omegaconf
  - pandas
  - scikit-learn
  - scikit-learn-intelex
  - submitit
  - termcolor
  - torchmetrics
  - kagglehub
  - peft
  - timm
  - pycocotools
  - pip
  - pip:
    - ftfy # needed for dino.txt
    - iopath
    - regex # needed for dino.txt